"""Ensure GeneralLedgerAccountDb table

Revision ID: 0eacf01a3b09
Revises: 6bad0d180d9b
Create Date: 2025-06-01 21:41:36.221261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eacf01a3b09'
down_revision = '6bad0d180d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('customer_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id_field', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('customer_tax_id', sa.String(length=30), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('billing_address_building_number', sa.String(length=10), nullable=True),
    sa.Column('billing_address_street_name', sa.String(length=200), nullable=True),
    sa.Column('billing_address_address_detail', sa.String(length=210), nullable=False),
    sa.Column('billing_address_city', sa.String(length=50), nullable=False),
    sa.Column('billing_address_postal_code', sa.String(length=20), nullable=False),
    sa.Column('billing_address_region', sa.String(length=50), nullable=True),
    sa.Column('billing_address_country', sa.String(length=20), nullable=False),
    sa.Column('shipping_address_building_number', sa.String(length=10), nullable=True),
    sa.Column('shipping_address_street_name', sa.String(length=200), nullable=True),
    sa.Column('shipping_address_address_detail', sa.String(length=210), nullable=True),
    sa.Column('shipping_address_city', sa.String(length=50), nullable=True),
    sa.Column('shipping_address_postal_code', sa.String(length=20), nullable=True),
    sa.Column('shipping_address_region', sa.String(length=50), nullable=True),
    sa.Column('shipping_address_country', sa.String(length=20), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=60), nullable=True),
    sa.Column('self_billing_indicator', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'customer_id_field', name='uq_user_customer_id')
    )
    op.create_table('gl_account_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id_field', sa.String(length=30), nullable=False),
    sa.Column('account_description', sa.String(length=100), nullable=False),
    sa.Column('opening_debit_balance', sa.Float(), nullable=False),
    sa.Column('opening_credit_balance', sa.Float(), nullable=False),
    sa.Column('closing_debit_balance', sa.Float(), nullable=False),
    sa.Column('closing_credit_balance', sa.Float(), nullable=False),
    sa.Column('grouping_category', sa.Enum('GR', 'GA', 'GM', 'AR', 'AA', 'AM', name='groupingcategoryenum'), nullable=False),
    sa.Column('grouping_code', sa.String(length=30), nullable=True),
    sa.Column('taxonomy_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id_field', name='uq_user_gl_account_id')
    )
    op.create_table('mapping_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_profile_name')
    )
    op.create_table('product_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Enum('PRODUTOS', 'SERVICOS', 'OUTROS', 'IMPOSTOS_ESPECIAIS_CONSUMO', 'IMPOSTOS_TAXAS_ENCARGOS', name='producttypeenum'), nullable=False),
    sa.Column('product_code', sa.String(length=60), nullable=False),
    sa.Column('product_group', sa.String(length=50), nullable=True),
    sa.Column('product_description', sa.String(length=200), nullable=False),
    sa.Column('product_number_code', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_code', name='uq_user_product_code')
    )
    op.create_table('saft_header_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_file_version', sa.String(length=10), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('tax_registration_number', sa.Integer(), nullable=False),
    sa.Column('tax_accounting_basis', sa.Enum('CONTABILIDADE', 'FATURACAO_TERCEIROS', 'FATURACAO', 'INTEGRADA', 'PARCIAL', 'RECIBOS', 'AUTOFATURACAO', 'DOCUMENTOS_TRANSPORTE', name='taxaccountingbasisenum'), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('business_name', sa.String(length=60), nullable=True),
    sa.Column('company_address_building_number', sa.String(length=10), nullable=True),
    sa.Column('company_address_street_name', sa.String(length=200), nullable=True),
    sa.Column('company_address_address_detail', sa.String(length=210), nullable=False),
    sa.Column('company_address_city', sa.String(length=50), nullable=False),
    sa.Column('company_address_postal_code', sa.String(length=20), nullable=False),
    sa.Column('company_address_region', sa.String(length=50), nullable=True),
    sa.Column('company_address_country', sa.String(length=2), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.Enum('EUR', name='currencycodeenum'), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('tax_entity', sa.String(length=20), nullable=False),
    sa.Column('product_company_tax_id', sa.String(length=30), nullable=False),
    sa.Column('software_certificate_number', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('product_version', sa.String(length=30), nullable=False),
    sa.Column('header_comment', sa.Text(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id_field', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('supplier_tax_id', sa.String(length=9), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('billing_address_building_number', sa.String(length=10), nullable=True),
    sa.Column('billing_address_street_name', sa.String(length=200), nullable=True),
    sa.Column('billing_address_address_detail', sa.String(length=210), nullable=False),
    sa.Column('billing_address_city', sa.String(length=50), nullable=False),
    sa.Column('billing_address_postal_code', sa.String(length=20), nullable=False),
    sa.Column('billing_address_region', sa.String(length=50), nullable=True),
    sa.Column('billing_address_country', sa.String(length=2), nullable=False),
    sa.Column('ship_from_address_building_number', sa.String(length=10), nullable=True),
    sa.Column('ship_from_address_street_name', sa.String(length=200), nullable=True),
    sa.Column('ship_from_address_address_detail', sa.String(length=210), nullable=True),
    sa.Column('ship_from_address_city', sa.String(length=50), nullable=True),
    sa.Column('ship_from_address_postal_code', sa.String(length=20), nullable=True),
    sa.Column('ship_from_address_region', sa.String(length=50), nullable=True),
    sa.Column('ship_from_address_country', sa.String(length=2), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=60), nullable=True),
    sa.Column('self_billing_indicator', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'supplier_id_field', name='uq_user_supplier_id')
    )
    op.create_table('field_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('saft_internal_field', sa.String(length=255), nullable=False),
    sa.Column('source_column_name', sa.String(length=255), nullable=False),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('transformation_rule', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['mapping_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_mapping')
    op.drop_table('supplier_db')
    op.drop_table('saft_header_data')
    op.drop_table('product_db')
    op.drop_table('mapping_profile')
    op.drop_table('gl_account_db')
    op.drop_table('customer_db')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
